"""Updated Models

Revision ID: 7d3955b56f64
Revises: 925307dc2ddb
Create Date: 2023-08-01 16:06:01.568122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3955b56f64'
down_revision = '925307dc2ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_column('students', 'birthday')
    # ### end Alembic commands ###
